language: c
compiler:
  - gcc
before_script:
  - git config --global user.email "carino@travis.org"
  - git config --global user.name "Carino build on Travis"
  - mkdir carino
  - cd carino
  - mkdir bin
  - curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
  - chmod a+x bin/repo
  - ./bin/repo init -u https://github.com/ncarrier/carino-manifest
  - ./bin/repo sync
  - export CARINO_VEHICLE=obstination_pc
script: ./tools/build.sh

