language: c
compiler:
  - gcc
before_script:
  - mkdir carino
  - cd carino
  - mkdir bin
  - curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
  - chmod a+x bin/repo
  - ./repo init -u https://github.com/ncarrier/carino-manifest
  - ./repo sync
  - export CARINO_VEHICLE=obstination_pc
script: ./tools/build.sh

